---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: uat
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: uat
  secretRef:
    name: flux-system
  url: ssh://git@github.com/christianackman/infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: uat
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./apps/
  prune: true
  sourceRef:
    kind: GitRepository
    name: uat
  validation: client
