apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: httpbin-2
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: httpbin
      version: 0.1.4
      sourceRef:
        kind: HelmRepository
        name: ackman
        namespace: flux-system
  values:
    replicaCount: 2
    podAnnotations:
      app: httpbin-2
